# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='launch_Date',
            new_name='launch_date',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='variant_Name',
            new_name='variant_name',
        ),
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
