# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20171113_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kitcarrelation',
            old_name='carid',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='kitcarrelation',
            old_name='kitid',
            new_name='kit',
        ),
    ]
